# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19a4a30183e61bc5c77ee5cc230448cb8397c5bdc8bd4b1c9d2eff75f3a4d0550da3797cf1a9a022b900e635ab3c6d37610be7ef90bd9bb1b0ff33f989074c90

test:
  secret_key_base: 8d22b4eac93613eaf59c7d970ca653dbef5693f7b10bb38f00ad800304c4a11be13013ab224abf98e820f21b6c1538460f6de454101560430faf342983875126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
